package org.opencds.cqf.fhir.cr.measure.common;

import ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException;
import org.hl7.fhir.instance.model.api.IBaseResource;

/**
 * Version-agnostic interface for scoring FHIR MeasureReports.
 *
 * <p>Implementations handle version-specific FHIR resource operations while
 * delegating scoring logic to {@link MeasureDefScorer}.
 *
 * @param <M> Measure resource type (e.g., org.hl7.fhir.r4.model.Measure)
 * @param <R> MeasureReport resource type (e.g., org.hl7.fhir.r4.model.MeasureReport)
 *
 * Generated by Claude Sonnet 4.5 on 2025-12-09.
 */
public interface IMeasureReportScoringFhirAdapter<M extends IBaseResource, R extends IBaseResource> {

    /**
     * Score a MeasureReport using the version-agnostic MeasureDefScorer.
     *
     * <p>Default implementation follows the pattern:
     * 1. Build MeasureDef from Measure structure
     * 2. Populate MeasureDef with counts from MeasureReport
     * 3. Score using MeasureDefScorer
     * 4. Copy scores back to MeasureReport
     *
     * @param measure the Measure resource defining scoring logic
     * @param measureReport the MeasureReport to score
     */
    default void score(M measure, R measureReport) {
        // Build MeasureDef from Measure
        MeasureDef measureDef = buildMeasureDef(measure);

        // Populate counts from MeasureReport
        populateMeasureDefFromReport(measureDef, measureReport);

        // Score using version-agnostic scorer
        getMeasureDefScorer().score(getMeasureUrl(measure), measureDef);

        // Copy scores back to MeasureReport
        copyScoresToReport(measureDef, measureReport);
    }

    /**
     * Get the MeasureDefScorer instance to use for scoring.
     *
     * @return the MeasureDefScorer
     */
    MeasureDefScorer getMeasureDefScorer();

    /**
     * Extract the measure URL from the Measure resource.
     *
     * @param measure the Measure resource
     * @return the measure URL
     */
    String getMeasureUrl(M measure);

    /**
     * Build a MeasureDef from the Measure structure.
     *
     * @param measure the Measure resource
     * @return the built MeasureDef
     */
    MeasureDef buildMeasureDef(M measure);

    /**
     * Populate MeasureDef with population counts from MeasureReport.
     * Creates synthetic subject resources to match the reported counts.
     *
     * @param measureDef the MeasureDef to populate
     * @param measureReport the MeasureReport with counts
     */
    void populateMeasureDefFromReport(MeasureDef measureDef, R measureReport);

    /**
     * Copy computed scores from MeasureDef back to MeasureReport.
     *
     * @param measureDef the MeasureDef with computed scores
     * @param measureReport the MeasureReport to update
     */
    void copyScoresToReport(MeasureDef measureDef, R measureReport);

    /**
     * Validate that MeasureDef and MeasureReport have matching group counts.
     *
     * @param measureDefGroupCount the number of groups in MeasureDef
     * @param measureReportGroupCount the number of groups in MeasureReport
     * @throws UnprocessableEntityException if group counts don't match
     */
    default void validateGroupCounts(int measureDefGroupCount, int measureReportGroupCount) {
        if (measureDefGroupCount != measureReportGroupCount) {
            throw new UnprocessableEntityException(String.format(
                    "MeasureDef group count (%d) does not match MeasureReport group count (%d)",
                    measureDefGroupCount, measureReportGroupCount));
        }
    }
}
