package org.opencds.cqf.fhir.cr.measure.common;

import ca.uhn.fhir.context.FhirVersionEnum;
import ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException;
import org.hl7.fhir.instance.model.api.IBaseResource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Version-agnostic utility for post-hoc scoring of FHIR MeasureReports.
 *
 * <p>This adapter is designed for scenarios where a MeasureReport has already been
 * populated with population counts (e.g., from a database or external system) but
 * needs scores calculated. It automatically detects the FHIR version and applies
 * the appropriate scoring logic.
 *
 * <h3>Use Cases:</h3>
 * <ul>
 *   <li>Scoring MeasureReports retrieved from persistent storage (e.g., cdr-cr project)</li>
 *   <li>Re-scoring MeasureReports after data corrections</li>
 *   <li>Batch scoring operations on historical MeasureReports</li>
 * </ul>
 *
 * <h3>Example Usage (cdr-cr project):</h3>
 * <pre>{@code
 * // Before (version-specific):
 * public void scoreMeasureReport(Measure theMeasure, MeasureReport theMeasureReport) {
 *     R4MeasureDefBuilder measureDefBuilder = new R4MeasureDefBuilder();
 *     R4MeasureReportScorer scorer = new R4MeasureReportScorer();
 *     scorer.score(theMeasure.getUrl(), measureDefBuilder.build(theMeasure), theMeasureReport);
 * }
 *
 * // After (version-agnostic):
 * public void scoreMeasureReport(Measure theMeasure, MeasureReport theMeasureReport) {
 *     MeasureReportScoringFhirAdapter.score(theMeasure, theMeasureReport);
 * }
 * }</pre>
 *
 * <h3>Architecture:</h3>
 * <ol>
 *   <li>Detect FHIR version from Measure resource</li>
 *   <li>Delegate to version-specific {@link IMeasureReportScoringFhirAdapter} implementation</li>
 *   <li>Build MeasureDef from Measure structure (version-specific)</li>
 *   <li>Extract population counts from MeasureReport into MeasureDef (version-specific)</li>
 *   <li>Call {@link MeasureDefScorer#score(String, MeasureDef)} (version-agnostic)</li>
 *   <li>Copy computed scores back to MeasureReport (version-specific)</li>
 * </ol>
 *
 * <p><strong>Thread Safety:</strong> This class is stateless and thread-safe.
 *
 * @see MeasureDefScorer
 * @see IMeasureReportScoringFhirAdapter
 * @see org.opencds.cqf.fhir.cr.measure.r4.R4MeasureReportScorer (deprecated)
 * @since 3.x.x
 *
 * Generated by Claude Sonnet 4.5 on 2025-12-09.
 */
public class MeasureReportScoringFhirAdapter {

    private static final Logger logger = LoggerFactory.getLogger(MeasureReportScoringFhirAdapter.class);

    // Shared MeasureDefScorer instance (stateless, thread-safe)
    private static final MeasureDefScorer MEASURE_DEF_SCORER = new MeasureDefScorer();

    // Version-specific scorer implementations
    private static final R4MeasureReportScoringFhirAdapter R4_SCORER =
            new R4MeasureReportScoringFhirAdapter(MEASURE_DEF_SCORER);
    private static final Dstu3MeasureReportScoringFhirAdapter DSTU3_SCORER =
            new Dstu3MeasureReportScoringFhirAdapter(MEASURE_DEF_SCORER);

    private MeasureReportScoringFhirAdapter() {
        // Static utility class
    }

    /**
     * Score a MeasureReport that already has population counts populated.
     *
     * <p>This method automatically detects the FHIR version and applies the appropriate
     * scoring logic. The MeasureReport is mutated in place with computed scores.
     *
     * @param measure the Measure resource defining scoring logic and improvement notation
     * @param measureReport the MeasureReport to score (must have population counts already set)
     * @throws UnprocessableEntityException if FHIR version not supported or resources incompatible
     * @throws IllegalArgumentException if measure or measureReport is null
     */
    public static void score(IBaseResource measure, IBaseResource measureReport) {
        if (measure == null) {
            throw new IllegalArgumentException("Measure cannot be null");
        }
        if (measureReport == null) {
            throw new IllegalArgumentException("MeasureReport cannot be null");
        }

        // Auto-detect FHIR version from measure
        FhirVersionEnum measureVersion = measure.getStructureFhirVersionEnum();
        FhirVersionEnum reportVersion = measureReport.getStructureFhirVersionEnum();

        // Verify versions match
        if (measureVersion != reportVersion) {
            throw new UnprocessableEntityException(String.format(
                    "Measure version (%s) does not match MeasureReport version (%s)", measureVersion, reportVersion));
        }

        logger.debug("Scoring MeasureReport using FHIR version: {}", measureVersion);

        // Delegate to version-specific scorer implementation
        switch (measureVersion) {
            case R4:
                R4_SCORER.score(
                        (org.hl7.fhir.r4.model.Measure) measure, (org.hl7.fhir.r4.model.MeasureReport) measureReport);
                break;
            case DSTU3:
                DSTU3_SCORER.score((org.hl7.fhir.dstu3.model.Measure) measure, (org.hl7.fhir.dstu3.model.MeasureReport)
                        measureReport);
                break;
            case R5:
                throw new UnprocessableEntityException("R5 scoring not yet implemented. Please use R4 or DSTU3.");
            default:
                throw new UnprocessableEntityException(
                        "Unsupported FHIR version for measure scoring: " + measureVersion);
        }
    }
}
