package org.opencds.cqf.fhir.cr.measure.common;

/**
 * Immutable cache holding pre-computed references for measure observation scoring.
 * Used by StratumDef to avoid redundant lookups during scoring.
 * <p>
 * Applicable to measures with MEASUREOBSERVATION populations linked to NUMERATOR
 * and DENOMINATOR populations (e.g., ratio measures with observations).
 * <p>
 * All-or-nothing semantics: both fields must be non-null or construction fails.
 * This ensures that if we cache observation references, we always have both the
 * numerator and denominator available.
 * <p>
 * Performance optimization: Pre-computing these references at construction time
 * eliminates O(n) lookups that would otherwise be repeated for every stratum
 * during scoring.
 * <p>
 * Generated by Claude Sonnet 4.5 on 2025-12-05 for measure observation stratum scoring optimization.
 */
public record MeasureObservationStratumCache(
        StratumPopulationDef numeratorObservation, StratumPopulationDef denominatorObservation) {

    /**
     * Compact constructor enforcing all-or-nothing semantics.
     *
     * @throws IllegalArgumentException if either parameter is null
     */
    public MeasureObservationStratumCache {
        if (numeratorObservation == null || denominatorObservation == null) {
            throw new IllegalArgumentException("Both numerator and denominator observations must be non-null");
        }
    }
}
