package org.opencds.cqf.fhir.cr.measure.common;

import jakarta.annotation.Nullable;

// Generated by Claude Sonnet 4.5 on 2025-11-27
/**
 * FHIR-version-agnostic representation of a Quantity.
 * Used for continuous variable measure scoring to avoid coupling to specific FHIR versions.
 *
 * @see CodeDef
 * @see ConceptDef
 */
public class QuantityDef {

    @Nullable
    private final Double value;

    @Nullable
    private final String unit;

    @Nullable
    private final String system;

    @Nullable
    private final String code;

    public QuantityDef(@Nullable Double value, @Nullable String unit, @Nullable String system, @Nullable String code) {
        this.value = value;
        this.unit = unit;
        this.system = system;
        this.code = code;
    }

    // Convenience constructor for value-only quantities
    public QuantityDef(Double value) {
        this(value, null, null, null);
    }

    @Nullable
    public Double value() {
        return value;
    }

    @Nullable
    public String unit() {
        return unit;
    }

    @Nullable
    public String system() {
        return system;
    }

    @Nullable
    public String code() {
        return code;
    }

    @Override
    public String toString() {
        return "QuantityDef{" + "value="
                + value + ", unit='"
                + unit + '\'' + ", system='"
                + system + '\'' + ", code='"
                + code + '\'' + '}';
    }
}
