package org.opencds.cqf.fhir.cr.measure.common;

import jakarta.annotation.Nullable;

// Generated by Claude Sonnet 4.5 on 2025-11-27
/**
 * FHIR-version-agnostic representation of a Quantity value.
 * Used for continuous variable measure scoring to avoid coupling to specific FHIR versions.
 *
 * @see CodeDef
 * @see ConceptDef
 */
public class QuantityDef {

    @Nullable
    private final Double value;

    public QuantityDef(@Nullable Double value) {
        this.value = value;
    }

    @Nullable
    public Double value() {
        return value;
    }

    @Override
    public String toString() {
        return "QuantityDef{value=" + value + "}";
    }
}
