library DMConcepts version '1.0.1'

using FHIR version '4.0.1'

/* Terminology */

valueset "Annual Wellness Visit": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.526.3.1240' version '1.0.1'
valueset "Diabetes": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.103.12.1001' version '1.0.1'
valueset "Diabetic Nephropathy": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.109.12.1004' version '1.0.1'
valueset "HbA1c Laboratory Test": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.198.12.1013' version '1.0.1'
valueset "Home Healthcare Services": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.101.12.1016' version '1.0.1'
valueset "Office Visit": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.101.12.1001' version '1.0.1'
valueset "Microalbumin Test": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.109.11.1011' version '1.0.1'
valueset "Preventive Care Services-Initial Office Visit, 18 and Up": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.101.12.1023' version '1.0.1'
valueset "Preventive Care Services - Established Office Visit, 18 and Up": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113883.3.464.1003.101.12.1025' version '1.0.1'
valueset "Urinalysis": 'http://cds.optum.com/dqm-diabetes/fhir/ValueSet/2.16.840.1.113762.1.4.1078.43' version '1.0.1'
