package org.opencds.cqf.fhir.cr.measure.fhir2deftest.r4;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.fhir2deftest.Fhir2DefUnifiedMeasureTestHandler;

/**
 * R4-specific Fhir2Def integration tests inspired by ContinuousVariableResourceMeasureObservationTest.
 * <p>
 * Tests the unified, version-agnostic test DSL handler for R4 measure evaluation,
 * focusing on Def object capture and assertion capabilities.
 * </p>
 *
 * @author Claude (Anthropic AI Assistant)
 * @since 4.1.0
 */
public class ContinuousVariableResourceMeasureObservationFhir2DefTest {

    // Gender stratifier value constants
    private static final String GENDER_MALE = "male";
    private static final String GENDER_FEMALE = "female";
    private static final String GENDER_UNKNOWN = "unknown";
    private static final String GENDER_OTHER = "other";

    // Age calculation constants for EncounterBasis tests
    public static final LocalDate ENCOUNTER_BASIS_MEASUREMENT_PERIOD_START = LocalDate.of(2024, 1, 1);

    private static final LocalDate BIRTHDATE_1940_JAN_01 = LocalDate.of(1940, Month.JANUARY, 1);
    private static final LocalDate BIRTHDATE_1950_JAN_01 = LocalDate.of(1950, Month.JANUARY, 1);
    private static final LocalDate BIRTHDATE_1960_JAN_01 = LocalDate.of(1960, Month.JANUARY, 1);

    private static final String AGE_STRATUM_1 = Integer.toString(computeAge(BIRTHDATE_1940_JAN_01));
    private static final String AGE_STRATUM_2 = Integer.toString(computeAge(BIRTHDATE_1950_JAN_01));
    private static final String AGE_STRATUM_3 = Integer.toString(computeAge(BIRTHDATE_1960_JAN_01));

    /**
     * Compute age in years from birthdate to measurement period start.
     *
     * @param birthDate the birth date
     * @return age in years
     */
    private static int computeAge(LocalDate birthDate) {
        return Period.between(birthDate, ENCOUNTER_BASIS_MEASUREMENT_PERIOD_START)
                .getYears();
    }

    /**
     * Test continuous variable measure with boolean basis and average aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisAvg
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisAvg() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisAvg")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and average aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisAvg
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisAvg() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisAvg")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with boolean basis and count aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisCount
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisCount() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisCount")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and count aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisCount
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisCount() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisCount")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with boolean basis and median aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisMedian
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisMedian() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMedian")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and median aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisMedian
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisMedian() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMedian")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with boolean basis and min aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisMin
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisMin() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMin")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and min aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisMin
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisMin() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMin")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with boolean basis and max aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisMax
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisMax() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMax")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and max aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisMax
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisMax() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMax")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with boolean basis and sum aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationBooleanBasisSum
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationBooleanBasisSum() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationBooleanBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisSum")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-gender")
                .hasStratumCount(4)
                .stratumByValue(GENDER_MALE)
                .hasValueDef(GENDER_MALE)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_UNKNOWN)
                .hasValueDef(GENDER_UNKNOWN)
                .hasSubjectCount(1)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("measure-population")
                .hasCount(1)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(1)
                .up()
                .up()
                .stratumByValue(GENDER_OTHER)
                .hasValueDef(GENDER_OTHER)
                .hasSubjectCount(3)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(3)
                .up()
                .population("measure-population")
                .hasCount(3)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(3)
                .up()
                .up()
                .stratumByValue(GENDER_FEMALE)
                .hasValueDef(GENDER_FEMALE)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }

    /**
     * Test continuous variable measure with encounter basis and sum aggregation.
     * Validates population counts and stratifier structure using Def assertions.
     * <p>
     * Based on: continuousVariableResourceMeasureObservationEncounterBasisSum
     * </p>
     */
    @Test
    void continuousVariableResourceMeasureObservationEncounterBasisSum() {
        Fhir2DefUnifiedMeasureTestHandler.given()
                .repositoryFor("r4/ContinuousVariableObservationEncounterBasis")
                .when()
                .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisSum")
                .captureDef()
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(11)
                .up()
                .population("measure-population")
                .hasCount(11)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(11)
                .up()
                .stratifier("stratifier-age")
                .hasStratumCount(3)
                .stratumByValue(AGE_STRATUM_1)
                .hasValueDef(AGE_STRATUM_1)
                .hasSubjectCount(2)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(2)
                .up()
                .population("measure-population")
                .hasCount(2)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(2)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_2)
                .hasValueDef(AGE_STRATUM_2)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4)
                .up()
                .up()
                .stratumByValue(AGE_STRATUM_3)
                .hasValueDef(AGE_STRATUM_3)
                .hasSubjectCount(4)
                .hasPopulationCount(4)
                .population("initial-population")
                .hasCount(4)
                .up()
                .population("measure-population")
                .hasCount(4)
                .up()
                .population("measure-population-exclusion")
                .hasCount(0)
                .up()
                .population("measure-observation")
                .hasCount(4);
    }
}
