package org.opencds.cqf.fhir.cr.measure.dstu3;

import static org.junit.jupiter.api.Assertions.*;

import org.hl7.fhir.dstu3.model.Quantity;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.common.QuantityDef;

// Generated by Claude Sonnet 4.5 on 2025-11-28
class Dstu3ContinuousVariableObservationConverterTest {

    @Test
    void testWrapNumberAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity(42.5);

        assertEquals(42.5, result.value());
        assertNull(result.unit());
        assertNull(result.system());
        assertNull(result.code());
    }

    @Test
    void testWrapIntegerAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity(42);

        assertEquals(42.0, result.value());
        assertNull(result.unit());
    }

    @Test
    void testWrapStringAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity("123.45");

        assertEquals(123.45, result.value());
        assertNull(result.unit());
    }

    @Test
    void testWrapInvalidStringThrowsException() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        assertThrows(IllegalArgumentException.class, () -> converter.wrapResultAsQuantity("not-a-number"));
    }

    @Test
    void testWrapDstu3QuantityAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        q.setValue(100.0);
        q.setUnit("mg");
        q.setSystem("http://unitsofmeasure.org");
        q.setCode("mg");

        QuantityDef result = converter.wrapResultAsQuantity(q);

        assertEquals(100.0, result.value());
        assertEquals("mg", result.unit());
        assertEquals("http://unitsofmeasure.org", result.system());
        assertEquals("mg", result.code());
    }

    @Test
    void testWrapDstu3QuantityWithoutValue() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        q.setUnit("mg");
        q.setSystem("http://unitsofmeasure.org");
        q.setCode("mg");
        // No value set

        QuantityDef result = converter.wrapResultAsQuantity(q);

        assertNull(result.value());
        assertEquals("mg", result.unit());
        assertEquals("http://unitsofmeasure.org", result.system());
        assertEquals("mg", result.code());
    }

    @Test
    void testWrapNullReturnsNull() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity(null);

        assertNull(result);
    }

    @Test
    void testWrapUnsupportedTypeThrowsException() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        assertThrows(IllegalArgumentException.class, () -> converter.wrapResultAsQuantity(new Object()));
    }

    @Test
    void testConvertQuantityDefToDstu3Quantity() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef qd = new QuantityDef(75.0, "mmHg", "http://unitsofmeasure.org", "mm[Hg]");

        Quantity result = converter.convertToFhirQuantity(qd);

        assertEquals(75.0, result.getValue().doubleValue());
        assertEquals("mmHg", result.getUnit());
        assertEquals("http://unitsofmeasure.org", result.getSystem());
        assertEquals("mm[Hg]", result.getCode());
    }

    @Test
    void testConvertQuantityDefWithValueOnly() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef qd = new QuantityDef(42.0);

        Quantity result = converter.convertToFhirQuantity(qd);

        assertEquals(42.0, result.getValue().doubleValue());
        assertNull(result.getUnit());
        assertNull(result.getSystem());
        assertNull(result.getCode());
    }

    @Test
    void testConvertNullQuantityDefReturnsNull() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        assertNull(converter.convertToFhirQuantity(null));
    }

    @Test
    void testRoundTripConversion() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity original = new Quantity();
        original.setValue(42.5);
        original.setUnit("kg");
        original.setSystem("http://unitsofmeasure.org");
        original.setCode("kg");

        QuantityDef qd = converter.wrapResultAsQuantity(original);
        Quantity result = converter.convertToFhirQuantity(qd);

        assertEquals(original.getValue(), result.getValue());
        assertEquals(original.getUnit(), result.getUnit());
        assertEquals(original.getSystem(), result.getSystem());
        assertEquals(original.getCode(), result.getCode());
    }

    @Test
    void testExtractQuantityDefFromNonQuantityReturnsNull() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.extractQuantityDef("not a quantity");

        assertNull(result);
    }

    @Test
    void testExtractQuantityDefFromDstu3Quantity() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        q.setValue(100.0);
        q.setUnit("mg");

        QuantityDef result = converter.extractQuantityDef(q);

        assertNotNull(result);
        assertEquals(100.0, result.value());
        assertEquals("mg", result.unit());
    }
}
