package org.opencds.cqf.fhir.cr.measure.dstu3;

import static org.junit.jupiter.api.Assertions.*;

import org.hl7.fhir.dstu3.model.Quantity;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.common.QuantityDef;

// Generated by Claude Sonnet 4.5 on 2025-11-27
class Dstu3ContinuousVariableObservationConverterTest {

    @Test
    void testWrapNumberAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity(42.5);

        assertEquals(42.5, result.value());
    }

    @Test
    void testWrapDstu3QuantityAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        q.setValue(100.0);

        QuantityDef result = converter.wrapResultAsQuantity(q);

        assertEquals(100.0, result.value());
    }

    @Test
    void testConvertQuantityDefToDstu3Quantity() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef qd = new QuantityDef(75.0);

        Quantity result = converter.convertToFhirQuantity(qd);

        assertEquals(75.0, result.getValue().doubleValue());
    }

    @Test
    void testRoundTripConversion() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity original = new Quantity();
        original.setValue(42.5);

        QuantityDef qd = converter.wrapResultAsQuantity(original);
        Quantity result = converter.convertToFhirQuantity(qd);

        assertEquals(original.getValue(), result.getValue());
    }

    @Test
    void testConvertNullQuantityDefReturnsNull() {
        assertNull(Dstu3ContinuousVariableObservationConverter.INSTANCE.convertToFhirQuantity(null));
    }

    @Test
    void testWrapNullReturnsNull() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity(null);

        assertNull(result);
    }

    @Test
    void testWrapStringAsQuantityDef() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.wrapResultAsQuantity("123.45");

        assertEquals(123.45, result.value());
    }

    @Test
    void testWrapInvalidStringThrowsException() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        assertThrows(IllegalArgumentException.class, () -> converter.wrapResultAsQuantity("not a number"));
    }

    @Test
    void testWrapUnsupportedTypeThrowsException() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        assertThrows(IllegalArgumentException.class, () -> converter.wrapResultAsQuantity(new Object()));
    }

    @Test
    void testExtractQuantityDefFromNonQuantityReturnsNull() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef result = converter.extractQuantityDef(42.5);

        assertNull(result);
    }

    @Test
    void testExtractQuantityDefFromDstu3Quantity() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        q.setValue(99.9);

        QuantityDef result = converter.extractQuantityDef(q);

        assertNotNull(result);
        assertEquals(99.9, result.value());
    }

    @Test
    void testExtractQuantityDefFromQuantityWithoutValue() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        Quantity q = new Quantity();
        // No value set

        QuantityDef result = converter.extractQuantityDef(q);

        assertNotNull(result);
        assertNull(result.value());
    }

    @Test
    void testConvertQuantityDefWithNullValue() {
        var converter = Dstu3ContinuousVariableObservationConverter.INSTANCE;

        QuantityDef qd = new QuantityDef(null);

        Quantity result = converter.convertToFhirQuantity(qd);

        assertNotNull(result);
        assertFalse(result.hasValue());
    }
}
