package org.opencds.cqf.fhir.cr.common;

import java.util.Set;

/**
 * Controls automatic extension propagation during PlanDefinition and ActivityDefinition application.
 * Policies supplement the processors' built-in exclusions; they do not validate extension contexts
 * or filter extensions explicitly generated by operation logic or dynamic values.
 * Implementations shared between processors must be thread-safe.
 */
@FunctionalInterface
public interface ExtensionPropagationPolicy {
    boolean shouldPropagate(ExtensionPropagationContext context);

    /** Preserves the existing URL selection, subject to the processor's built-in exclusions. */
    static ExtensionPropagationPolicy legacy() {
        return context -> true;
    }

    /** Excludes the given exact URLs. The supplied set is defensively copied. */
    static ExtensionPropagationPolicy excludeUrls(Set<String> urls) {
        var excluded = Set.copyOf(urls);
        return context -> !excluded.contains(context.extensionUrl());
    }

    /** Permits only the given exact URLs. An empty set permits no automatic copies. */
    static ExtensionPropagationPolicy allowOnlyUrls(Set<String> urls) {
        var allowed = Set.copyOf(urls);
        return context -> allowed.contains(context.extensionUrl());
    }

    /** Disables automatic extension copying at the supported propagation sites. */
    static ExtensionPropagationPolicy none() {
        return context -> false;
    }
}
