library HTNConcepts version '1.0.1'

using FHIR version '4.0.1'

/* Terminology */

valueset "Annual Wellness Visit": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.3.1240' version '1.0.1'
valueset "Blood Pressure Panel": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-BloodPressurePanel' version '1.0.1'
valueset "Chronic Kidney Disease, Stage 5": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.3.1002' version '1.0.1'
valueset "Diastolic Blood Pressure": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.2.1045' version '1.0.1'
valueset "End Stage Renal Disease": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.3.353' version '1.0.1'
valueset "ESRD Monthly Outpatient Services": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.109.12.1014' version '1.0.1'
valueset "Essential Hypertension": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.104.12.1011' version '1.0.1'
valueset "Home Healthcare Services": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.101.12.1016' version '1.0.1'
valueset "Kidney Transplant": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.109.12.1012' version '1.0.1'
valueset "Kidney Transplant Recipient": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.109.12.1029' version '1.0.1'
valueset "Office Visit": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.101.12.1001' version '1.0.1'
valueset "Pregnancy": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.3.378' version '1.0.1'
valueset "Preventive Care Services-Initial Office Visit, 18 and Up": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.101.12.1023' version '1.0.1'
valueset "Preventive Care Services - Established Office Visit, 18 and Up": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.464.1003.101.12.1025' version '1.0.1'
valueset "Systolic Blood Pressure": 'http://cds.optum.com/dqm-hypertension/fhir/ValueSet/HTN-2.16.840.1.113883.3.526.2.1044' version '1.0.1'
