package org.opencds.cqf.fhir.cr.measure.dstu3;

import org.hl7.fhir.dstu3.model.Measure;
import org.hl7.fhir.dstu3.model.MeasureReport;
import org.opencds.cqf.fhir.cr.measure.common.GroupDef;
import org.opencds.cqf.fhir.cr.measure.common.IMeasureToReportScoreFhirHandler;
import org.opencds.cqf.fhir.cr.measure.common.MeasureDef;
import org.opencds.cqf.fhir.cr.measure.common.MeasureDefScorer;
import org.opencds.cqf.fhir.cr.measure.common.PopulationDef;
import org.opencds.cqf.fhir.cr.measure.common.StratifierDef;
import org.opencds.cqf.fhir.cr.measure.common.StratumDef;

/**
 * DSTU3-specific implementation of IMeasureToReportScoreFhirHandler.
 *
 * <p>This record implementation handles DSTU3 FHIR resources and delegates
 * scoring logic to {@link MeasureDefScorer}.
 *
 * Generated by Claude Sonnet 4.5 on 2025-12-12.
 */
public record Dstu3MeasureToReportScoreFhirHandler(MeasureDefScorer measureDefScorer)
        implements IMeasureToReportScoreFhirHandler<Measure, MeasureReport> {

    @Override
    public MeasureDefScorer getMeasureDefScorer() {
        return measureDefScorer;
    }

    @Override
    public String getMeasureUrl(Measure measure) {
        return measure.getUrl();
    }

    @Override
    public MeasureDef buildMeasureDef(Measure measure) {
        var builder = new Dstu3MeasureDefBuilder();
        return builder.build(measure);
    }

    @Override
    public void populateMeasureDefFromReport(MeasureDef measureDef, MeasureReport measureReport) {
        var groups = measureDef.groups();
        var reportGroups = measureReport.getGroup();

        validateGroupCounts(groups.size(), reportGroups.size());

        for (int i = 0; i < groups.size(); i++) {
            populateGroupFromReport(groups.get(i), reportGroups.get(i));
        }
    }

    /**
     * Populate a single GroupDef with population counts from a MeasureReport group.
     */
    private void populateGroupFromReport(GroupDef groupDef, MeasureReport.MeasureReportGroupComponent reportGroup) {
        for (var reportPop : reportGroup.getPopulation()) {
            populatePopulationFromReport(groupDef, reportPop);
        }
    }

    /**
     * Populate a single PopulationDef with synthetic subjects to match the reported count.
     */
    private void populatePopulationFromReport(
            GroupDef groupDef, MeasureReport.MeasureReportGroupPopulationComponent reportPop) {
        String popCode = reportPop.hasCode() && !reportPop.getCode().getCoding().isEmpty()
                ? reportPop.getCode().getCoding().get(0).getCode()
                : null;
        if (popCode == null) {
            return;
        }
        int count = reportPop.getCount();

        // Find matching PopulationDef and populate with synthetic subjects
        groupDef.populations().stream()
                .filter(p -> p.type().toCode().equals(popCode))
                .forEach(p -> addSyntheticSubjects(p, count));
    }

    /**
     * Add synthetic subject resources to a PopulationDef to match a count.
     */
    private void addSyntheticSubjects(PopulationDef populationDef, int count) {
        for (int j = 0; j < count; j++) {
            populationDef.addResource("synthetic-subject-" + j, new Object());
        }
    }

    @Override
    public void copyScoresToReport(MeasureDef measureDef, MeasureReport measureReport) {
        var groups = measureDef.groups();
        var reportGroups = measureReport.getGroup();

        for (int i = 0; i < groups.size(); i++) {
            copyGroupScoresToReport(groups.get(i), reportGroups.get(i));
        }
    }

    /**
     * Copy scores from a single GroupDef to a MeasureReport group.
     */
    private void copyGroupScoresToReport(GroupDef groupDef, MeasureReport.MeasureReportGroupComponent reportGroup) {
        // Copy group-level score with improvement notation applied
        Double groupScore = groupDef.getMeasureScore();
        if (groupScore != null && groupScore >= 0) {
            reportGroup.setMeasureScore(groupScore);
        }

        // Copy stratifier scores if present
        if (reportGroup.hasStratifier() && !groupDef.stratifiers().isEmpty()) {
            copyStratifierScoresToReport(groupDef, reportGroup);
        }
    }

    /**
     * Copy stratifier scores from GroupDef to DSTU3 MeasureReport group.
     */
    private void copyStratifierScoresToReport(
            GroupDef groupDef, MeasureReport.MeasureReportGroupComponent reportGroup) {
        for (int stratIdx = 0; stratIdx < reportGroup.getStratifier().size(); stratIdx++) {
            copyStratifierScoreToReport(groupDef, reportGroup.getStratifier().get(stratIdx), stratIdx);
        }
    }

    /**
     * Copy scores for a single stratifier.
     */
    private void copyStratifierScoreToReport(
            GroupDef groupDef, MeasureReport.MeasureReportGroupStratifierComponent reportStratifier, int stratIdx) {
        // Find matching StratifierDef (by index for now)
        if (stratIdx >= groupDef.stratifiers().size()) {
            return;
        }
        StratifierDef stratifierDef = groupDef.stratifiers().get(stratIdx);

        for (int stratumIdx = 0; stratumIdx < reportStratifier.getStratum().size(); stratumIdx++) {
            copyStratumScoreToReport(
                    stratifierDef, reportStratifier.getStratum().get(stratumIdx), stratumIdx);
        }
    }

    /**
     * Copy score for a single stratum.
     */
    private void copyStratumScoreToReport(
            StratifierDef stratifierDef, MeasureReport.StratifierGroupComponent reportStratum, int stratumIdx) {
        if (stratumIdx >= stratifierDef.getStratum().size()) {
            return;
        }
        StratumDef stratumDef = stratifierDef.getStratum().get(stratumIdx);

        // Copy stratum score with improvement notation applied
        Double stratumScore = stratumDef.getScore();
        if (stratumScore != null && stratumScore >= 0) {
            reportStratum.setMeasureScore(stratumScore);
        }
    }
}
