package org.opencds.cqf.fhir.cr.measure.r4;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.common.ContinuousVariableObservationAggregateMethod;
import org.opencds.cqf.fhir.cr.measure.r4.Measure.Given;

@SuppressWarnings("squid:S2699")
public class ContinuousVariableResourceMeasureObservationTest {

    public static final LocalDate ENCOUNTER_BASIS_MEASUREMENT_PERIOD_START = LocalDate.of(2024, 1, 1);

    private static final LocalDate _1940_JAN_01 = LocalDate.of(1940, Month.JANUARY, 1);
    private static final LocalDate _1950_JAN_01 = LocalDate.of(1950, Month.JANUARY, 1);
    private static final LocalDate _1960_JAN_01 = LocalDate.of(1960, Month.JANUARY, 1);

    private static final int EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1 = computeAge(_1940_JAN_01);
    private static final int EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2 = computeAge(_1950_JAN_01);
    private static final int EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3 = computeAge(_1960_JAN_01);

    private static final Given GIVEN_BOOLEAN_BASIS =
            Measure.given().repositoryFor("ContinuousVariableObservationBooleanBasis");
    private static final Given GIVEN_ENCOUNTER_BASIS =
            Measure.given().repositoryFor("ContinuousVariableObservationEncounterBasis");

    @Nested
    class Avg {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisAvg() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisAvg")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .hasAggregationResult(74.0)
                    .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.AVG)
                    .up()
                    .hasScore(74.0)
                    .stratifier("stratifier-gender")
                    .hasStratumCount(4)
                    .up()
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .hasAggregationResultsExtensionValue(74.0)
                    .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.AVG)
                    .up()
                    .hasScore("74.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("82.33333333333333")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("64.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("77.33333333333333")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("67.75")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4);
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisAvg() {
            // Test data summary:
            // - 11 total encounters across 10 patients (patient-9 has 2 encounters)
            // - 2 cancelled encounters (patient-6, patient-7) are excluded
            // - 9 encounters remain after exclusion
            // - Total duration: 2416 minutes, avg = 268.44...
            //
            // By age stratum (using Age Function per encounter):
            // - Stratum 84 (born 1940): patient-0 (120 min), patient-1 (120 min) = 2 encounters, avg 120.0
            // - Stratum 74 (born 1950): patient-2 (540), patient-3 (420), patient-4 (840), patient-5 (120)
            //   = 4 encounters, avg 480.0
            // - Stratum 64 (born 1960): patient-6 (cancelled), patient-7 (cancelled), patient-8 (15),
            //   patient-9-enc-1 (121), patient-9-enc-2 (120) = 5 encounters, 2 excluded, 3 remaining
            //   = 3 encounters after exclusion, avg 85.33...

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisAvg")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-observation")
                    .hasCount(9)
                    .hasAggregationResult(268.44444444444446)
                    .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.AVG)
                    .up()
                    .hasScore(268.44444444444446)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-observation")
                    .hasCount(9)
                    .hasAggregationResultsExtensionValue(268.44444444444446)
                    .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.AVG)
                    .up()
                    .hasScore("268.44444444444446")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    // Stratum "84" has 2 encounters with avg age 60 each = 120.0 avg
                    .stratumByText("84")
                    .hasScore("120.0")
                    .up()
                    .up()
                    .up()
                    .report();
        }
    }

    @Nested
    class Count {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisCount() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisCount")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore(11.0)
                    .stratifier("stratifier-gender")
                    .hasStratumCount(4)
                    .up()
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore("11.0")
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("3.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("1.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("3.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("4.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisCount() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisCount")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(10)
                    .up()
                    .hasScore(9.0) // 11 total - 2 exclusions = 9
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population")
                    .hasCount(12) // Initial count before exclusions
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3) // 2 encounters excluded
                    .up()
                    .population("measure-observation")
                    .hasCount(9) // 12 - 3 = 9
                    .up()
                    .hasScore("9.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("2.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(2)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("4.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasScore("3.0") // 5 - 2 exclusions = 3
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5) // Full count before exclusions
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(2) // 2 exclusions in this stratum
                    .up()
                    .population("measure-observation")
                    .hasCount(3) // 5 - 2 = 3
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }
    }

    @Nested
    class Median {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisMedian() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMedian")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore(79.0)
                    .stratifier("stratifier-gender")
                    .hasStratumCount(4)
                    .up()
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore("79.0")
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("84.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("64.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("79.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("66.5")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisMedian() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMedian")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(10)
                    .up()
                    .hasScore(120.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3) // 2 encounters excluded
                    .up()
                    .population("measure-observation")
                    .hasCount(9) // 12 - 3 = 9
                    .up()
                    .hasScore("120.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("120.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(2)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("480.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasScore("120.0") // Median of remaining 3 observations
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(2) // 2 exclusions
                    .up()
                    .population("measure-observation")
                    .hasCount(3) // 5 - 2 = 3
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }
    }

    @Nested
    class Min {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisMin() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMin")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(11)
                    .up()
                    .hasScore(54.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore("54.0")
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("79.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("64.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("69.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("54.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisMin() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMin")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(10)
                    .up()
                    .hasScore(15.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3) // 2 encounters excluded
                    .up()
                    .population("measure-observation")
                    .hasCount(9) // 12 - 3 = 9
                    .up()
                    .hasScore("15.0") // min across all non-excluded observations
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("120.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(2)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("120.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasScore("15.0") // Min of remaining observations
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(2) // 2 exclusions
                    .up()
                    .population("measure-observation")
                    .hasCount(3) // 5 - 2 = 3
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }
    }

    @Nested
    class Max {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisMax() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisMax")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(11)
                    .up()
                    .hasScore(84.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore("84.0")
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("84.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("64.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("84.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("84.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisMax() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisMax")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(10)
                    .up()
                    .hasScore(840.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3) // 2 encounters excluded
                    .up()
                    .population("measure-observation")
                    .hasCount(9) // 12 - 3 = 9
                    .up()
                    .hasScore("840.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("120.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(2)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("840.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasScore("121.0") // Max of remaining observations
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(2) // 2 exclusions
                    .up()
                    .population("measure-observation")
                    .hasCount(3) // 5 - 2 = 3
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }
    }

    @Nested
    class Sum {

        @Test
        void continuousVariableResourceMeasureObservationBooleanBasisSum() {

            GIVEN_BOOLEAN_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationBooleanBasisSum")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(11)
                    .up()
                    .hasScore(814.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population")
                    .hasCount(11)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(11)
                    .up()
                    .hasScore("814.0")
                    .stratifierById("stratifier-gender")
                    .hasStratumCount(4)
                    .stratumByText("male")
                    .hasValue("male")
                    .hasScore("247.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("unknown")
                    .hasValue("unknown")
                    .hasScore("64.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .up()
                    .up()
                    .stratumByText("other")
                    .hasValue("other")
                    .hasScore("232.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population")
                    .hasCount(3)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(3)
                    .up()
                    .up()
                    .stratumByText("female")
                    .hasValue("female")
                    .hasScore("271.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population")
                    .hasCount(4)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisSum() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisSum")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("measure-population")
                    .hasSubjectCount(10)
                    .up()
                    .hasScore(2416.0) // 2536 - 120 (2 exclusions with total age 120)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population")
                    .hasCount(12)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(3) // 2 encounters excluded
                    .up()
                    .population("measure-observation")
                    .hasCount(9) // 12 - 3 = 9
                    .up()
                    .hasScore("2416.0") // 2536 - 120
                    .stratifierById("stratifier-age")
                    .hasStratumCount(3)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("240.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(2)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("1920.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(4)
                    .up()
                    .up()
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_3))
                    .hasScore("256.0") // 376 - 120 (2 exclusions) = 256
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population")
                    .hasCount(5)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(2) // 2 exclusions
                    .up()
                    .population("measure-observation")
                    .hasCount(3) // 5 - 2 = 3
                    .up()
                    .up()
                    .up()
                    .up()
                    .report();
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisSpecificSubjectIdSum() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisSum")
                    .subject("patient-3")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population")
                    .hasSubjectCount(1)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population-exclusion")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-observation")
                    .hasAggregationResult(420.0)
                    .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore(420.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .logReportJson()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(2)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .hasAggregationResultsExtensionValue(420.0)
                    .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore("420.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(1)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("420.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(1);
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisAnotherSpecificSubjectId1Sum() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisSum")
                    .subject("patient-0")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population")
                    .hasSubjectCount(1)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population-exclusion")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-observation")
                    .hasAggregationResult(120.0)
                    .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore(120.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .logReportJson()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(1)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .hasAggregationResultsExtensionValue(120.0)
                    .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore("120.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(1)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_1))
                    .hasScore("120.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population")
                    .hasCount(1)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(0)
                    .up()
                    .population("measure-observation")
                    .hasCount(1);
        }

        @Test
        void continuousVariableResourceMeasureObservationEncounterBasisAnotherSpecificSubjectId2Sum() {

            GIVEN_ENCOUNTER_BASIS
                    .when()
                    .measureId("ContinuousVariableResourceMeasureObservationEncounterBasisSum")
                    .subject("patient-3")
                    .evaluate()
                    .then()
                    // MeasureDef assertions (pre-scoring) - verify internal state after processing
                    .def()
                    .hasNoErrors()
                    .firstGroup()
                    .population("initial-population")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population")
                    .hasSubjectCount(1)
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-population-exclusion")
                    .hasNoAggregationResult()
                    .up()
                    .population("measure-observation")
                    .hasAggregationResult(420.0)
                    .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore(420.0)
                    .up()
                    .up()
                    // MeasureReport assertions (post-scoring) - verify FHIR resource output
                    .report()
                    .logReportJson()
                    .firstGroup()
                    .population("initial-population")
                    .hasCount(2)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .hasNoAggregationResultsExtensionValue()
                    .hasNoAggregateMethodExtension()
                    .up()
                    .population("measure-observation")
                    .hasCount(1)
                    .hasAggregationResultsExtensionValue(420.0)
                    .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                    .up()
                    .hasScore("420.0")
                    .stratifierById("stratifier-age")
                    .hasStratumCount(1)
                    .stratumByText(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasValue(Integer.toString(EXPECTED_ENCOUNTER_BASIS_AGE_STRATUM_2))
                    .hasScore("420.0")
                    .hasPopulationCount(4)
                    .population("initial-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population")
                    .hasCount(2)
                    .up()
                    .population("measure-population-exclusion")
                    .hasCount(1)
                    .up()
                    .population("measure-observation")
                    .hasCount(1);
        }
    }

    private static int computeAge(LocalDate birthDate) {
        return Period.between(birthDate, ENCOUNTER_BASIS_MEASUREMENT_PERIOD_START)
                .getYears();
    }
}
