package org.opencds.cqf.fhir.cr.measure.r4;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.hl7.fhir.r4.model.Period;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.r4.Measure.Given;

public class MeasureSupportingEvidenceTest {

    private static final Given given = Measure.given().repositoryFor("MeasureTest");
    private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX");

    @Test
    void ratioSupportingEvidence() throws ParseException {

        given.when()
                .measureId("RatioGroupBooleanAllPopulationsSuppEvidence")
                .subject("patient-9")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .firstGroup()
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("denominator")
                .hasCount(1)
                .getExtDef("always true")
                .extensionDefHasResults()
                .up()
                .getExtDef("Denominator Resource")
                .extensionDefHasResults()
                .up()
                .up()
                .population("denominator-exclusion")
                .hasCount(0)
                .up()
                .population("numerator-exclusion")
                .hasCount(0)
                .up()
                .population("numerator")
                .hasCount(1)
                .up()
                .hasScore(1.0)
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .population("initial-population")
                .hasCount(1)
                .up()
                .population("denominator")
                .hasCount(1)
                .getPopulationExtension("always true")
                .hasBooleanValue(true)
                .up()
                .getPopulationExtension("Denominator Resource")
                .hasListResourceIdItem("Encounter/patient-9-encounter-2")
                .hasListResourceIdItem("Encounter/patient-9-encounter-1")
                .up()
                .getPopulationExtension("list of boolean")
                .hasListBooleanItem(true)
                .hasListBooleanItem(false)
                .up()
                .getPopulationExtension("string")
                .hasStringValue("string test")
                .up()
                .getPopulationExtension("date")
                .hasStringValue("2026-01-01")
                .up()
                .getPopulationExtension("decimal")
                .hasDecimalValue(31.31)
                .up()
                .getPopulationExtension("number")
                .hasIntegerValue(31)
                .up()
                .getPopulationExtension("list of dates")
                .hasListStringItem("2024-01-01")
                .hasListStringItem("2024-01-02")
                .hasListStringItem("2024-01-03")
                .up()
                .getPopulationExtension("list of numbers")
                .hasListIntegerItem(31)
                .hasListIntegerItem(88)
                .hasListIntegerItem(11)
                .up()
                .getPopulationExtension("list of string")
                .hasListStringItem("test1")
                .hasListStringItem("test2")
                .hasListStringItem("test3")
                .up()
                .getPopulationExtension("test tuple")
                .hasTupleInteger("number", 31)
                .hasTupleListStringItem("dates", "2024-01-01")
                .hasTupleListStringItem("dates", "2024-01-02")
                .hasTupleListStringItem("dates", "2024-01-03")
                .hasTupleString("birthYear", "string test")
                .up()
                .getPopulationExtension("interval")
                .hasPeriodValue(new Period()
                        .setStart(DATE_FORMAT.parse("2024-01-01T00:00:00-00:00"))
                        .setEnd(DATE_FORMAT.parse("2024-12-31T23:59:59-00:00")))
                .up()
                .getPopulationExtension("TestIntervalList")
                .hasListPeriodItem(new Period()
                        .setStart(DATE_FORMAT.parse("2024-01-01T00:00:00-00:00"))
                        .setEnd(DATE_FORMAT.parse("2024-01-31T23:59:59-00:00")))
                .hasListPeriodItem(new Period()
                        .setStart(DATE_FORMAT.parse("2024-02-01T00:00:00-00:00"))
                        .setEnd(DATE_FORMAT.parse("2024-02-29T23:59:59-00:00")))
                .up()
                .getPopulationExtension("TestDecimalList")
                .hasListDecimalItem(1.5)
                .hasListDecimalItem(2.75)
                .hasListDecimalItem(0.33333)
                .up()
                .getPopulationExtension("test code")
                .hasStringValue(
                        "Code { code: M, system: http://hl7.org/fhir/v3/AdministrativeGender, version: null, display: Male }")
                .up()
                .getPopulationExtension("EmptyListExample")
                .hasStringValue("null")
                .up()
                .getPopulationExtension("NullExample")
                .hasStringValue("null")
                .up()
                .getPopulationExtension("PatientRes")
                .hasResourceIdValue("Patient/patient-9")
                .up()
                .getPopulationExtension("list test tuple")
                .up()
                .up()
                .population("denominator-exclusion")
                .hasCount(0)
                .up()
                .population("numerator-exclusion")
                .hasCount(0)
                .up()
                .population("numerator")
                .hasCount(1)
                .up()
                .hasScore("1.0")
                .up()
                .report();
    }
}
