package org.opencds.cqf.fhir.cr.measure.r4;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import ca.uhn.fhir.rest.server.exceptions.InvalidRequestException;
import org.hl7.fhir.r4.model.MeasureReport.MeasureReportStatus;
import org.junit.jupiter.api.Test;
import org.opencds.cqf.fhir.cr.measure.common.ContinuousVariableObservationAggregateMethod;
import org.opencds.cqf.fhir.cr.measure.common.MeasurePopulationType;
import org.opencds.cqf.fhir.cr.measure.common.MeasureScoring;
import org.opencds.cqf.fhir.cr.measure.r4.Measure.Given;
import org.opencds.cqf.fhir.cr.measure.r4.Measure.When;

/**
 * Summary of generated Patients and their Encounter durations.
 *
 * All Encounters share the period:
 * - **Start:** 2024-01-01T01:00:00Z
 * - **End:**   2024-01-01T03:00:00Z
 * → **Duration:** 120 minutes
 *
 * ## Encounter Durations (Markdown Table)
 *
 * | Patient ID         | DOB          | Age (yrs) | Encounter ID                   | Status       | Duration (min) |
 * |--------------------|--------------|-----------|--------------------------------|--------------|----------------|
 * | patient-0          | 1985-06-16   | 39        | patient-0-encounter-1          | in-progress  | 120            |
 * | patient-1          | 1988-01-11   | 36        | patient-1-encounter-1          | in-progress  | 120            |
 * | patient-2          | 1985-06-16   | 39        | patient-2-encounter-1          | arrived      | 120            |
 * | patient-3          | 1988-01-11   | 36        | patient-3-encounter-1          | arrived      | 120            |
 * | patient-4          | 1985-06-16   | 39        | patient-4-encounter-1          | triaged      | 120            |
 * | patient-5          | 1988-01-11   | 36        | patient-5-encounter-1          | triaged      | 120            |
 * | patient-6          | 1985-06-16   | 39        | patient-6-encounter-1          | cancelled    | 120            |
 * | patient-7          | 1988-01-11   | 36        | patient-7-encounter-1          | cancelled    | 120            |
 * | patient-8          | 1985-06-16   | 39        | patient-8-encounter-1          | finished     | 120            |
 * | patient-9          | 1988-01-11   | 36        | patient-9-encounter-1          | finished     | 30             |
 * | patient-9          | 1988-01-11   | 36        | patient-9-encounter-2          | in-progress  | 180            |
 *
 * ## Encounter Durations
 *
 * | Metric | Value |
 * |--------|-------|
 * | Count  | 11    |
 * | Sum    | 1290  |
 * | Avg    | 117.27   |
 * | Min    | 30   |
 * | Max    | 180   |
 * | Median | 120   |
 *
 * ## Age Statistics (as of 2024-12-31)
 *
 * | Metric | Value |
 * |--------|-------|
 * | Count  | 10    |
 * | Sum    | 375   |
 * | Avg    | 37.5  |
 * | Min    | 36    |
 * | Max    | 39    |
 * | Median | 37.5  |
 */
@SuppressWarnings("squid:S2699")
class MeasureScoringTypeRatioContVariableTest {

    private static final Given given = Measure.given().repositoryFor("MeasureTest");

    /**
     * Test 1:
     * ResourceBasis
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableResourceBasisSum() {

        given.when()
                .measureId("RatioContVarResourceSum")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(1050.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(150.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.14285714285714285) // 150/1050  sum(30,120) /sum(30, 180, 120, 120, 120, 120, 120, 120, 120)
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .hasCount(11)
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(1050.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(150.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore(
                        "0.14285714285714285") // 150/1050  sum(30,120) /sum(30, 180, 120, 120, 120, 120, 120, 120, 120)
                .up()
                .report();
    }

    /**
     * Test 2:
     * ResourceBasis
     * aggregateMethod Numerator: Count
     * aggregateMethod Denominator: Count
     */
    @Test
    void ratioContinuousVariableResourceBasisCount() {

        given.when()
                .measureId("RatioContVarResourceCount")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasCount(11)
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(9.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(2.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReference("numerator")
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(9.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(2.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.2222222222222222) // 2/9
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasCount(11)
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(9.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(2.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.COUNT)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.2222222222222222") // 2/9
                .up()
                .report();
    }

    /**
     * Test 3:
     * ResourceBasis
     * aggregateMethod Numerator: Avg
     * aggregateMethod Denominator: Avg
     */
    @Test
    void ratioContinuousVariableResourceBasisAvg() {

        given.when()
                .measureId("RatioContVarResourceAvg")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(116.66666666666667)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(75.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.6428571428571428) // 75/116.6666 avg(30,120)=75,avg(180,30,120,120,120,120,120,120,120)
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(116.66666666666667)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(75.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.6428571428571428") // 75/116.6666 avg(30,120)=75,avg(180,30,120,120,120,120,120,120,120)
                .up()
                .report();
    }

    /**
     * Test 4:
     * ResourceBasis
     * aggregateMethod Numerator: Min
     * aggregateMethod Denominator: Min
     */
    @Test
    void ratioContinuousVariableResourceBasisMin() {

        given.when()
                .measureId("RatioContVarResourceMin")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(30.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MIN)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(30.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MIN)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(1.0) // 30/30
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(30.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MIN)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(30.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MIN)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("1.0") // 30/30
                .up()
                .report();
    }

    /**
     * Test 5:
     * ResourceBasis
     * aggregateMethod Numerator: Max
     * aggregateMethod Denominator: Max
     */
    @Test
    void ratioContinuousVariableResourceBasisMax() {

        given.when()
                .measureId("RatioContVarResourceMax")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(180.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MAX)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(120.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MAX)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.6666666666666666) // 120/180
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(180.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MAX)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(120.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MAX)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.6666666666666666") // 120/180
                .up()
                .report();
    }

    /**
     * Test 6:
     * ResourceBasis
     * aggregateMethod Numerator: Median
     * aggregateMethod Denominator: Median
     */
    @Test
    void ratioContinuousVariableResourceBasisMedian() {

        given.when()
                .measureId("RatioContVarResourceMedian")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(120.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MEDIAN)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(75.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.MEDIAN)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.625) // 75/120 Median(30,120)=75
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .hasStatus(MeasureReportStatus.COMPLETE)
                .firstGroup()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(120.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MEDIAN)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(75.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.MEDIAN)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.625") // 75/120 Median(30,120)=75
                .up()
                .report();
    }
    /**
     * Test 7:
     * BooleanBasis
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableBooleanBasisSum() {

        given.when()
                .measureId("RatioContVarBooleanSum")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasCount(10)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasCount(10) // final Denominator = 8 (10-2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasCount(2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasCount(0)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(8)
                .hasAggregationResult(300.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(75.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.25) // 36,39=75, 36,39,36,39,36,39,36,39=300 ===>.25
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(10)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(10) // final Denominator = 8 (10-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(8) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(300.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(75.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.25") // 36,39=75, 36,39,36,39,36,39,36,39=300 ===>.25
                .up()
                .report();
    }
    /**
     * Test 8:
     * ResourceBasis
     * Mixed Aggregate Methods
     * aggregateMethod Numerator: avg
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableResourceBasisMix() {

        given.when()
                .measureId("RatioContVarResourceMix")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(1050.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(75.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.07142857142857142) // 75/1050 avg/sum  avg(30, 120)= 75, sum(30,
                // 180,120,120,120,120,120,120,120)=1050,
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(1050.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(75.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.AVG)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.07142857142857142") // 75/1050 avg/sum  avg(30, 120)= 75, sum(30,
                // 180,120,120,120,120,120,120,120)=1050,
                .up()
                .report();
    }
    /**
     * Test 9:
     * Mixed Basis on MeasureObservations, This should Error due to mismatch of basis on criteria expression function
     * aggregateMethod Numerator: Sum Age
     * aggregateMethod Denominator: Sum Encounter Durations
     */
    @Test
    void ratioContinuousVariableMixBasisSum() {

        given.when()
                .measureId("RatioContVarMixBasisSum")
                .evaluate()
                .then()
                .def()
                .hasError(
                        "Measure observation criteria expression: MeasureObservationBoolean is missing a function parameter matching the population-basis")
                .up()
                .hasStatus(MeasureReportStatus.ERROR)
                .hasContainedOperationOutcomeMsg(
                        "Measure observation criteria expression: MeasureObservationBoolean is missing a function parameter matching the population-basis")
                .def()
                .firstGroup()
                .hasNullScore()
                .up()
                .up()
                .firstGroup()
                .hasMeasureScore(false)
                .up()
                .report();
    }

    /**
     * Test 10:
     * Den=0 scenario
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableNoDenominator() {
        given.when()
                .measureId("RatioContVarResourceSum")
                .subject("Patient/patient-7")
                .evaluate()
                .then()
                .def()
                .hasNoErrors()
                .firstGroup()
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(1)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(1) // final Denominator = 8 (10-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(0) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasCriteriaReference("numerator")
                .up()
                .hasNullScore()
                .up()
                .up()
                .firstGroup()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(1)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(1) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(0) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0) // we remove exclusions in these counts so users can see final Observation count used
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0) // we remove exclusions in these counts so users can see final Observation count used
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasMeasureScore(false)
                .up()
                .report();
    }

    /**
     * Test 11:
     * Den>0, Num=0 scenario
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableNoNumerator() {
        given.when()
                .measureId("RatioContVarResourceSum2")
                .subject("Patient/patient-9")
                .evaluate()
                .then()
                .def()
                .firstGroup()
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(2) // final Denominator = 8 (10-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(1)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(1) // final Numerator = 2
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                // If there's no numerator, we still want to capture the aggregate result
                .hasAggregationResult(210.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasCriteriaReference("numerator")
                .up()
                .hasNullScore()
                .up()
                .up()
                .firstGroup()
                .population("initial-population")
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCount(2) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCount(1)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCount(1) // final Numerator = 2
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(210.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(0) // we remove exclusions in these counts so users can see final Observation count used
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasMeasureScore(false)
                .up()
                .report();
    }
    /**
     * Test 12:
     * no den defined
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: NA
     */
    @Test
    void ratioContinuousVariableNoDenDef() {
        var when = given.when()
                .measureId("RatioContVarResourceSumError")
                .subject("Patient/patient-9")
                .evaluate();
        var exception = assertThrows(InvalidRequestException.class, when::then);
        assertTrue(exception
                .getMessage()
                .contains("Ratio Continuous Variable requires 2 Measure Observations defined, you have: 1"));
    }

    /**
     * Test 12:
     * bad den defined
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: NA
     */
    @Test
    void ratioContinuousVariableBadDenDef() {
        final When when = given.when()
                .measureId("RatioContVarResourceSumError2")
                .subject("Patient/patient-9")
                .evaluate();
        var expectedException = assertThrows(InvalidRequestException.class, when::then);

        assertTrue(expectedException.getMessage().contains("no matching criteria reference was found for extension"));
    }

    /**
     * Test 13:
     * test RCV Stratifier Scoring
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableStratifierResource() {
        given.when()
                .measureId("RatioContVarResourceSumValueStrat")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(9) // final Numerator = 9
                .hasAggregateMethodNA()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(9)
                .hasAggregationResult(1050.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(7)
                .hasAggregationResult(810.0)
                .hasAggregateMethod(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.7714285714285715) // 810/1050  sum(30,180,120,120,120,120,120) /sum(30, 180, 120, 120, 120,
                // 120, 120, 120, 120)
                .firstStratifier()
                .hasStratumCount(2)
                .stratumByValue("35")
                .hasScore(0.7894736842105263) // 450/570 Sum(180,30,120,120)/sum(180,30,120,120,120)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(6)
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(6) // final Denominator = 9 (11-2)
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(5) // final Numerator = 2
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(5)
                .up()
                .population("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(5)
                .up()
                .population("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4)
                .up()
                .up()
                .stratumByValue("38")
                .hasScore(0.75) // sum(120,120,120)/sum(120,120,120,120)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 4 (5-1)
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(4) // final Numerator = 3
                .up()
                .up()
                .up()
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(11)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(11) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(9) // final Numerator = 9
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCount(9) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(1050.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCount(7) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(810.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore(
                        "0.7714285714285715") // 810/1050  sum(30,180,120,120,120,120,120) /sum(30, 180, 120, 120, 120,
                // 120, 120, 120, 120)
                .firstStratifier()
                .hasStratumCount(2)
                .stratum("35")
                .hasScore("0.7894736842105263") // 450/570 Sum(180,30,120,120)/sum(180,30,120,120,120)
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(6)
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(6) // final Denominator = 9 (11-2)
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(5) // final Numerator = 2
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(5) // we remove exclusions in these counts so users can see final Observation count used
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4)
                .up()
                .up()
                .stratum("38")
                .hasScore("0.75") // sum(120,120,120)/sum(120,120,120,120)
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 4 (5-1)
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(4) // final Numerator = 3
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4) // we remove exclusions in these counts so users can see final Observation count used
                .hasNoStratumPopulationSubjectResults()
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(3)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .up()
                .up()
                .up()
                .report();
    }

    /**
     * Test 13:
     * test RCV Stratifier Scoring with Boolean basis
     * aggregateMethod Numerator: Sum
     * aggregateMethod Denominator: Sum
     */
    @Test
    void ratioContinuousVariableStratifierBoolean() {
        given.when()
                .measureId("RatioContVarBooleanSumValueStrat")
                .evaluate()
                .then()
                // MeasureDef assertions (pre-scoring) - verify internal state after processing
                .def()
                .hasNoErrors()
                .hasMeasureScoring(MeasureScoring.RATIO)
                .firstGroup()
                .hasNoGroupLevelScoring()
                .hasEffectiveScoring(MeasureScoring.RATIO)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(10)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(10) // final Denominator = 9 (11-2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 9
                .hasNoAggregationResult()
                .hasNoCriteriaReference()
                .up()
                .populationById("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(8)
                .hasAggregationResult(300.0)
                .hasCriteriaReference("denominator")
                .up()
                .populationById("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2)
                .hasAggregationResult(75.0)
                .hasCriteriaReference("numerator")
                .up()
                .hasScore(0.25) // 75 / 300  sum(36,39) /sum(39,36,39,36,39,36,39,36)
                .firstStratifier()
                .hasStratumCount(2)
                .stratumByValue("M")
                .hasScore(0.25) //  Sum(36)/sum(36,36,36,36)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 9 (11-2)
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .up()
                .population("numerator")
                .hasCount(1) // final Numerator = 2
                .up()
                .population("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4)
                .up()
                .population("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(1)
                .up()
                .up()
                .stratumByValue("F")
                .hasScore(0.25) // sum(39)/sum(39,39,39,39)
                .population("initial-population")
                .hasType(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .up()
                .population("denominator")
                .hasType(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 4 (5-1)
                .up()
                .population("denominator-exclusion")
                .hasType(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasType(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .up()
                .population("numerator")
                .hasType(MeasurePopulationType.NUMERATOR)
                .hasCount(1) // final Numerator = 3
                .up()
                .population("observation-den")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4)
                .up()
                .population("observation-num")
                .hasType(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(1)
                .up()
                .up()
                .up()
                .up()
                .up()
                // MeasureReport assertions (post-scoring) - verify FHIR resource output
                .report()
                .firstGroup()
                .hasNoGroupScoringExt()
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(10)
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(10) // final Denominator = 9 (11-2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(2)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(2) // final Numerator = 9
                .hasNoAggregationResultsExtensionValue()
                .hasNoAggregateMethodExtension()
                .hasNoCriteriaReferenceExtension()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(8) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(300.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("denominator")
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(2) // we remove exclusions in these counts so users can see final Observation count used
                .hasAggregationResultsExtensionValue(75.0)
                .hasAggregateMethodExtension(ContinuousVariableObservationAggregateMethod.SUM)
                .hasCriteriaReferenceExtension("numerator")
                .up()
                .hasScore("0.25") // 75 / 300  sum(36,39) /sum(39,36,39,36,39,36,39,36)
                .firstStratifier()
                .hasStratumCount(2)
                .stratum("M")
                .hasScore("0.25") //  Sum(36)/sum(36,36,36,36)
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 9 (11-2)
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(1) // final Numerator = 2
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4) // we remove exclusions in these counts so users can see final Observation count used
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(1)
                .up()
                .up()
                .stratum("F")
                .hasScore("0.25") // sum(39)/sum(39,39,39,39)
                .population("initial-population")
                .hasCode(MeasurePopulationType.INITIALPOPULATION)
                .hasCount(5)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .population("denominator")
                .hasCode(MeasurePopulationType.DENOMINATOR)
                .hasCount(5) // final Denominator = 4 (5-1)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .population("denominator-exclusion")
                .hasCode(MeasurePopulationType.DENOMINATOREXCLUSION)
                .hasCount(1)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .population("numerator-exclusion")
                .hasCode(MeasurePopulationType.NUMERATOREXCLUSION)
                .hasCount(0)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .population("numerator")
                .hasCode(MeasurePopulationType.NUMERATOR)
                .hasCount(1) // final Numerator = 3
                .hasNoStratumPopulationSubjectResults()
                .up()
                .populationId("observation-den")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(4) // we remove exclusions in these counts so users can see final Observation count used
                .hasNoStratumPopulationSubjectResults()
                .up()
                .populationId("observation-num")
                .hasCode(MeasurePopulationType.MEASUREOBSERVATION)
                .hasCount(1)
                .hasNoStratumPopulationSubjectResults()
                .up()
                .up()
                .up()
                .up()
                .report();
    }
}
