package org.opencds.cqf.fhir.cr.measure.common;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.Test;

// Generated by Claude Sonnet 4.5 on 2025-11-27
class QuantityDefTest {

    @Test
    void testQuantityDefCreation() {
        QuantityDef qd = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");

        assertEquals(42.5, qd.value());
        assertEquals("mg", qd.unit());
        assertEquals("http://unitsofmeasure.org", qd.system());
        assertEquals("mg", qd.code());
    }

    @Test
    void testQuantityDefWithValueOnly() {
        QuantityDef qd = new QuantityDef(100.0);

        assertEquals(100.0, qd.value());
        assertNull(qd.unit());
        assertNull(qd.system());
        assertNull(qd.code());
    }

    @Test
    void testQuantityDefWithNullValue() {
        QuantityDef qd = new QuantityDef(null, "mg", "http://unitsofmeasure.org", "mg");

        assertNull(qd.value());
        assertEquals("mg", qd.unit());
        assertEquals("http://unitsofmeasure.org", qd.system());
        assertEquals("mg", qd.code());
    }

    @Test
    void testQuantityDefAllNulls() {
        QuantityDef qd = new QuantityDef(null, null, null, null);

        assertNull(qd.value());
        assertNull(qd.unit());
        assertNull(qd.system());
        assertNull(qd.code());
    }

    // Enhanced by Claude Sonnet 4.5 on 2025-11-28
    @Test
    void testInstanceEqualityDifferentObjects() {
        // Two QuantityDefs with identical values are NOT equal (instance equality)
        QuantityDef qd1 = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");
        QuantityDef qd2 = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");

        assertNotEquals(qd1, qd2, "QuantityDefs with identical values should NOT be equal (instance equality)");
        assertNotSame(qd1, qd2, "QuantityDefs are different instances");
    }

    // Enhanced by Claude Sonnet 4.5 on 2025-11-28
    @Test
    void testInstanceEqualitySameReference() {
        // Same reference IS equal
        QuantityDef qd1 = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");
        QuantityDef qd2 = qd1;

        assertEquals(qd1, qd2, "Same reference should be equal");
        assertSame(qd1, qd2, "Same reference");
    }

    // Enhanced by Claude Sonnet 4.5 on 2025-11-28
    @Test
    void testCollectionProcessing() {
        // Two QuantityDefs with identical values should be treated as different in collections
        QuantityDef qd1 = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");
        QuantityDef qd2 = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");

        Set<QuantityDef> set = new HashSet<>();
        set.add(qd1);
        set.add(qd2);

        assertEquals(2, set.size(), "Set should contain 2 distinct instances despite identical values");
    }

    // Enhanced by Claude Sonnet 4.5 on 2025-11-28
    @Test
    void testToString() {
        QuantityDef qd = new QuantityDef(42.5, "mg", "http://unitsofmeasure.org", "mg");

        String result = qd.toString();

        assertNotNull(result);
        assertTrue(result.contains("42.5"));
        assertTrue(result.contains("mg"));
        assertTrue(result.contains("http://unitsofmeasure.org"));
    }
}
