package org.opencds.cqf.fhir.cr.measure.common;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.Test;

// Generated by Claude Sonnet 4.5 on 2025-11-27
class QuantityDefTest {

    @Test
    void testQuantityDefCreation() {
        QuantityDef qd = new QuantityDef(42.5);

        assertEquals(42.5, qd.value());
    }

    @Test
    void testQuantityDefWithNullValue() {
        QuantityDef qd = new QuantityDef(null);

        assertNull(qd.value());
    }

    @Test
    void testInstanceEqualityDifferentObjects() {
        // Two QuantityDefs with identical values are NOT equal (instance equality)
        QuantityDef qd1 = new QuantityDef(42.5);
        QuantityDef qd2 = new QuantityDef(42.5);

        assertNotEquals(qd1, qd2);
        assertNotSame(qd1, qd2);
    }

    @Test
    void testInstanceEqualitySameReference() {
        // Same reference IS equal
        QuantityDef qd = new QuantityDef(42.5);

        assertEquals(qd, qd);
        assertSame(qd, qd);
    }

    @Test
    void testSetContainsMultipleInstancesWithSameValue() {
        // Set should contain multiple QuantityDefs with same value (instance equality)
        QuantityDef qd1 = new QuantityDef(42.5);
        QuantityDef qd2 = new QuantityDef(42.5);
        QuantityDef qd3 = new QuantityDef(42.5);

        Set<QuantityDef> set = new HashSet<>();
        set.add(qd1);
        set.add(qd2);
        set.add(qd3);

        // All three instances should be in the set
        assertEquals(3, set.size());
        assertTrue(set.contains(qd1));
        assertTrue(set.contains(qd2));
        assertTrue(set.contains(qd3));
    }

    @Test
    void testSetRemovalOnlyRemovesSpecificInstance() {
        // Removing one instance should not remove other instances with same value
        QuantityDef qd1 = new QuantityDef(42.5);
        QuantityDef qd2 = new QuantityDef(42.5);
        QuantityDef qd3 = new QuantityDef(42.5);

        Set<QuantityDef> set = new HashSet<>();
        set.add(qd1);
        set.add(qd2);
        set.add(qd3);

        // Remove qd2 specifically
        set.remove(qd2);

        // qd1 and qd3 should still be in the set
        assertEquals(2, set.size());
        assertTrue(set.contains(qd1));
        assertFalse(set.contains(qd2));
        assertTrue(set.contains(qd3));
    }

    @Test
    void testToString() {
        QuantityDef qd = new QuantityDef(42.5);

        assertEquals("QuantityDef{value=42.5}", qd.toString());
    }

    @Test
    void testToStringWithNull() {
        QuantityDef qd = new QuantityDef(null);

        assertEquals("QuantityDef{value=null}", qd.toString());
    }
}
