name: Check PR
on:
    pull_request:
      types: [opened, reopened, synchronize]

permissions:
    checks: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gradle:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
            fetch-depth: 0 #shallow clone for better sonarqube analysis
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.fhir
          key: ${{ runner.os }}-fhir-${{ hashFiles('**/*.*') }}
          restore-keys: |
            ${{ runner.os }}-fhir-
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: matrix.os == 'ubuntu-latest'
        with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
            distribution: 'temurin'
            java-version: '21'
      - uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
      - name: Resolve linked builds
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew resolveLinkedBuilds
      - name: Compile
        run: ./gradlew assemble
      - name: Run tests
        run: ./gradlew build
      - name: SonarCloud Analysis
        if: matrix.os == 'ubuntu-latest'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_QUBE_022026 }}
        run: ./gradlew sonar -Dsonar.token=$SONAR_TOKEN
      - name: Publish test report
        uses: mikepenz/action-junit-report@3a81627bfac62268172037048872e8ebd4207e6d # v6.4.1
        if: (success() || failure()) && matrix.os == 'ubuntu-latest'
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
          job_name: "Check PR"
